### ISSUE TITLE
读取数据库只显示第一条数据的问题

### ISSUE THREAD

**Issue by lzh545** [zlgopen/awtk-database-repository#1]
李工你好，awtk-database-repository用最新的源码编译后，运行student_list_mvvm的demo，效果如图，只显示数据库的第一条数据，请问这个问题怎么解决？

![微信图片_20220727090802](https://user-images.githubusercontent.com/28924342/181138598-a9f5da12-e37b-4f6f-8841-678b75615c5c.png)

**Comment by xianjimli** [comment]
麻烦更新一下：awtk-database-repository和awtk-widget-table-view-mvvm，重新编译和生成资源。谢谢

**Comment by lzh545** [comment]
> 麻烦更新一下：awtk-database-repository和awtk-widget-table-view-mvvm，重新编译和生成资源。谢谢

李工你好，读取问题已解决，还有个新问题，列表拉到最后的时候会很卡，具体可看图的打印
![邮洽图片20220802105059](https://user-images.githubusercontent.com/28924342/182281505-273465cd-d01a-407e-83ac-3c0a4d53a81c.jpg)

**Comment by xianjimli** [comment]
你再更新试试。谢谢

**Comment by lzh545** [comment]
> 你再更新试试。谢谢

解决了，谢谢李工
